"""
Download routes for MP3 files
Author: AI Assistant
Purpose: Provide downloadable MP3 files for songs generated by ElevenLabs
Note: This is an isolated module and does not modify existing functionality
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
import os
from config.settings import settings

router = APIRouter(prefix="/api/downloads", tags=["downloads"])


@router.get("/song/{song_id}")
async def download_song(song_id: str):
    """
    Download a generated song as MP3
    
    Args:
        song_id: The UUID of the generated song (without .mp3 extension)
        
    Returns:
        FileResponse: MP3 file with proper headers for download
    """
    try:
        # Construct file path
        filename = f"{song_id}.mp3"
        file_path = os.path.join(settings.UPLOAD_DIR, "music", filename)
        
        # Check if file exists
        if not os.path.exists(file_path):
            raise HTTPException(
                status_code=404, 
                detail=f"Song file not found: {song_id}"
            )
        
        # Return file with download headers
        return FileResponse(
            path=file_path,
            media_type="audio/mpeg",
            filename=filename,
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "Cache-Control": "no-cache",
            }
        )
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error downloading song: {str(e)}"
        )


@router.get("/song/{song_id}/stream")
async def stream_song(song_id: str):
    """
    Stream a generated song (inline playback)
    
    Args:
        song_id: The UUID of the generated song (without .mp3 extension)
        
    Returns:
        FileResponse: MP3 file with inline headers
    """
    try:
        # Construct file path
        filename = f"{song_id}.mp3"
        file_path = os.path.join(settings.UPLOAD_DIR, "music", filename)
        
        # Check if file exists
        if not os.path.exists(file_path):
            raise HTTPException(
                status_code=404, 
                detail=f"Song file not found: {song_id}"
            )
        
        # Return file with inline headers (for playback)
        return FileResponse(
            path=file_path,
            media_type="audio/mpeg",
            filename=filename,
            headers={
                "Content-Disposition": f'inline; filename="{filename}"',
                "Accept-Ranges": "bytes",
            }
        )
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error streaming song: {str(e)}"
        )

